version: '3'
services:
  app:
    build:
      context: .
    container_name: tasklist
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tasklist_db?currentSchema=tasklist
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=beeline1099
    ports:
      - '8080:8080'

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=beeline1099
      - POSTGRES_DB=tasklist_db
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d